# Generated by Django 4.2.6 on 2023-10-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_player_last_online'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lobby',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Lobbies'},
        ),
        migrations.AddField(
            model_name='player',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_lobbies', to='base.player'),
        ),
    ]
